name: react_built_redux
version: 0.0.1
description:
   A provider and connect function for built_redux
authors:
- David Marne <davemarne@gmail.com>
homepage: https://github.com/davidmarne/react_built_redux
dependencies:
  built_redux: "^0.1.2"
  over_react: "^1.6.0"
  recompose_dart: "^0.0.9"

dev_dependencies:
  coverage: "^0.7.3"
  dart_dev: "^1.0.0"
  dart_style: ">=0.2.0 <0.3.0"
  dartdoc: ">=0.8.0 <=0.10.0"
  test: "^0.12.0"


dependency_overrides:
  react:
    git:
      url: git://github.com/greglittlefield-wf/react-dart.git
      ref: context

transformers:
  - over_react
  - $dart2js

environment:
  sdk: ">=1.17.1 <2.0.0"
